config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

  root "pages#home"
  get "/error", to: "errors#handle404"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/search", to: "pages#search"
  # get "/manage_users", to: "manage_users#new"
  # get "/user_destroy", to: "manage_users#destroy"

  # get "/view_category", to: "manage_categories#index"
  # get "/new_category", to: "manage_categories#new"
  # post "/new_category", to: "manage_categories#create"
  # get "/delete_category", to: "manage_categories#delete"
  
  # get "/new_tour", to: "manage_tours#new"
  # post "/new_tour", to: "manage_tours#create"
  # get "/view_tour", to: "manage_tours#view_all"
  # get "/delete_tour", to: "manage_tours#destroy"

  # get "/new_tour_details", to: "manage_tour_details#new"
  # post "/new_tour_details", to: "manage_tour_details#create"
  # get "/view_tour_details", to: "manage_tour_details#view"
  # get "/delete_tour_details", to: "manage_tour_details#destroy"

  # get "/new_booking_request", to: "booking_request#new"
  # post "/new_booking_request", to: "booking_request#booking"
  # get "/view_booking_request", to: "booking_request#view_all"
  # get "/view_all_booking_request", to: "booking_request#view_all_by_admin"
  # get "/delete_booking_request", to: "booking_request#destroy"

  # get "/review_tour", to: "reviews#new"
  # post "/review_tour", to: "reviews#create"
  # get "/view_all_review", to:"reviews#view_all_reviews"
  # get "/view_tour_review", to: "reviews#view_tour_reviews"
  # get "/edit_my_reviews", to: "reviews#edit"
  # post "/edit_my_reviews", to: "reviews#update"
  # get "/delete_my_reviews", to: "reviews#destroy"
  # post "/like_review", to: "reviews#like"
  # post "/unlike_review", to: "reviews#unlike"

  # post "/pay", to: "payments#pay"

  # get "/revenue", to: "manage_revenue#index"

  get "/view_my_booking", to: "self_management#view_my_booking"
  get "/view_my_review", to: "self_management#view_my_review"
  get "/view_my_information", to: "self_management#view_my_information"
  get "/view_other_user_information", to: "self_management#view_other_user_information"
  resources :self_management, only: [:edit, :update]
  resources :tour_details, only: [:new]
  resources :ratings, only: [:new]
  resources :bookings, only: [:new, :destroy]
  resources :likes, only: [:new, :destroy]
  resources :comments, only: [:new, :destroy]
  resources :users, only: [:new, :edit, :update, :create]
  resources :manage_users, only: [:new, :edit, :update]
  resources :payments, only: [:create]

  namespace :admin do
    resources :users, except: []
    resources :reviews, except: []
    resources :categories, except: []
    resources :tours, except: []
    resources :tour_details, except: []
    resources :bookings, except: []
    resources :payments, only: [:index]
  end
end
end

app/models/tour.rb
class Tour < ApplicationRecord
  mount_uploader :image, TourUploader
  belongs_to :user
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_many :tour_details, dependent: :destroy
  has_many :ratings, dependent: :destroy
  scope :order_by_time_desc, ->{order(created_at: :desc)}
  validates :user_id, numericality:
   {greater_than_or_equal_to: Settings.positive}
  validates :category_id, numericality:
   {greater_than_or_equal_to: Settings.positive}
  validates :name, presence: true,
  length: {maximum: Settings.name_maximum_length}
  validates :description, presence: true,
  length: {maximum: Settings.description_maximum_length}
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::BaseController
  def new
    @tour = current_user.tours.build(category_id: params[:id])
  end

  def index
    @tour = Tour.order_by_time_desc.paginate(page: params[:page], per_page: 15)
  end

  def create
    @tour = current_user.tours.create(tour_params)
    if @tour.save
      flash[:success] = t("controller.flash.create_tour_successfully")
      redirect_to admin_tours_path
    else
      render :new
    end
  end

  def destroy
    @tour_destroy = Tour.find_by_id params[:id]
    if @tour_destroy.destroy
      flash[:success] = t("controller.flash.delete_tour_successfully")
    else
      flash[:danger] = t("controller.flash.delete_tour_failed")
    end
    redirect_to admin_tours_path
  end

  private

  def tour_params
    params.require(:tour).permit(
      :name, :description, :user_id, :category_id, :image
    )
  end
end

app/views/admin/tours/index.html.erb
<%= will_paginate @tour %>
<div class="container">
  <div class="">
    <table class="table table-striped custab">
      <thead>
        <tr>
          <th> <%= t("views.tag.tour_id") %> </th>
          <th> <%= t("views.tag.tour_name") %> </th>
          <th> <%= t("views.tag.description") %> </th>
          <th> <%= t("views.tag.category_name") %> </th>
          <th>  <%= t("views.tag.created_by") %> </th>
          <th class="text-center"> <%= t("views.tag.action") %> </th>
        </tr>
      </thead>
      <% @tour.each do |tour| %>
        <tr>
          <td> <%= tour.id %> </td>
          <td> <%= tour.name %> </td>
          <td> <%= tour.description %> </td>
          <td> <%= tour.category.name %> </td>
          <td> <%= tour.user.name %> </td>
          <td class="text-center">
            <%= link_to admin_tour_details_path(id: tour.id), class: "btn btn-info btn-xs" do %>
              <span class="glyphicon glyphicon-edit"> <%= t("views.tag.view_tour_detail") %> </span>
            <% end %>
            <%= link_to new_admin_tour_detail_path(id: tour.id), class: "btn btn-info btn-xs" do %>
              <span class="glyphicon glyphicon-edit"> <%= t("views.tag.create_tour_detail") %> </span>
            <% end%>
            <%= link_to admin_tour_path(id: tour.id), method: :DELETE, class: "btn btn-danger btn-xs" do %>
              <span class="glyphicon glyphicon-remove"> <%= t("views.tag.delete_tour") %> </span>
            <% end%>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/tours/new.html.erb
<%= form_for(@tour,url: admin_tours_path) do |f| %>
  <%= render "shared/form_error_messages", object: @tour %>
  <%= f.label t("views.tag.name") %>
  <%= f.text_field :name %>
  <%= f.label t("views.tag.description") %>
  <%= f.text_field :description %>
  <%= f.file_field :image %>
  <%= f.hidden_field :category_id %>
  <%= f.submit t("views.tag.create_tour"), class: "btn btn-primary" %>
<% end %>