config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

  root "pages#home"
  get "/error", to: "errors#handle404"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/search", to: "pages#search"
  # get "/manage_users", to: "manage_users#new"
  # get "/user_destroy", to: "manage_users#destroy"

  # get "/view_category", to: "manage_categories#index"
  # get "/new_category", to: "manage_categories#new"
  # post "/new_category", to: "manage_categories#create"
  # get "/delete_category", to: "manage_categories#delete"
  
  # get "/new_tour", to: "manage_tours#new"
  # post "/new_tour", to: "manage_tours#create"
  # get "/view_tour", to: "manage_tours#view_all"
  # get "/delete_tour", to: "manage_tours#destroy"

  # get "/new_tour_details", to: "manage_tour_details#new"
  # post "/new_tour_details", to: "manage_tour_details#create"
  # get "/view_tour_details", to: "manage_tour_details#view"
  # get "/delete_tour_details", to: "manage_tour_details#destroy"

  # get "/new_booking_request", to: "booking_request#new"
  # post "/new_booking_request", to: "booking_request#booking"
  # get "/view_booking_request", to: "booking_request#view_all"
  # get "/view_all_booking_request", to: "booking_request#view_all_by_admin"
  # get "/delete_booking_request", to: "booking_request#destroy"

  # get "/review_tour", to: "reviews#new"
  # post "/review_tour", to: "reviews#create"
  # get "/view_all_review", to:"reviews#view_all_reviews"
  # get "/view_tour_review", to: "reviews#view_tour_reviews"
  # get "/edit_my_reviews", to: "reviews#edit"
  # post "/edit_my_reviews", to: "reviews#update"
  # get "/delete_my_reviews", to: "reviews#destroy"
  # post "/like_review", to: "reviews#like"
  # post "/unlike_review", to: "reviews#unlike"

  # post "/pay", to: "payments#pay"

  # get "/revenue", to: "manage_revenue#index"

  get "/view_my_booking", to: "self_management#view_my_booking"
  get "/view_my_review", to: "self_management#view_my_review"
  get "/view_my_information", to: "self_management#view_my_information"
  get "/view_other_user_information", to: "self_management#view_other_user_information"
  resources :self_management, only: [:edit, :update]
  resources :tour_details, only: [:new]
  resources :ratings, only: [:new]
  resources :bookings, only: [:new, :destroy]
  resources :likes, only: [:new, :destroy]
  resources :comments, only: [:new, :destroy]
  resources :users, only: [:new, :edit, :update, :create]
  resources :manage_users, only: [:new, :edit, :update]
  resources :payments, only: [:create]

  namespace :admin do
    resources :users, except: []
    resources :reviews, except: []
    resources :categories, except: []
    resources :tours, except: []
    resources :tour_details, except: []
    resources :bookings, except: []
    resources :payments, only: [:index]
  end
end
end

app/models/tour_detail.rb
class TourDetail < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  has_many :bookings, dependent: :destroy
  scope :order_by_time_desc, ->{order(created_at: :desc)}
  scope :t_id, (lambda do |id|
    where(
      tour_id: id
    )
  end)

  validates :price, numericality:
   {greater_than_or_equal_to: Settings.minimum_price}
  validates :tour_total, numericality:
   {greater_than_or_equal_to: Settings.minimum_tour_total}
  validates :user_id, numericality:
   {greater_than_or_equal_to: Settings.positive}
  validates :tour_id, numericality:
    {
      greater_than_or_equal_to: Settings.positive,
      less_than_or_equal_to: Settings.maximum_tour_total
    }
  validate :validate

  def validate
    if time_start < Time.zone.now
      errors.add(:time_start, I18n.t("validate.validate_time"))
    end
    if time_end <= time_start
      errors.add(:time_end, I18n.t("validate.validate_time_end"))
    end
    true # never return false or the validation fails
  end
end

app/controllers/admin/tour_details_controller.rb
class Admin::TourDetailsController < Admin::BaseController
  before_action :load_tour_detail, only: [:destroy]
  def new
    @tour_details = current_user.tour_details.build(tour_id: params[:id])
  end

  def index
    @tour_details = TourDetail.t_id(params[:id]).order_by_time_desc.paginate(
      page: params[:page], per_page: Settings.tour_detail_per_page
    )
  end

  def create
    @tour_details = current_user.tour_details.create(user_params)
    if @tour_details.save
      flash[:success] = t("controller.flash.tour_detail_created_successfully")
      redirect_to admin_tour_details_path(id: params[:tour_detail][:tour_id])
    else
      flash[:danger] = t("controller.flash.tour_detail_created_failed")
      render :new
    end
  end

  def destroy
    if @tour_detail.destroy
      flash[:success] = t("controller.flash.delete_tour_detail_successfully")
    else
      flash[:danger] = t("controller.flash.delete_tour_detail_failed")
    end
    redirect_to admin_tours_path
  end

  private

  def user_params
    params.require(:tour_detail).permit(
      :price, :tour_total, :time_start, :time_end, :user_id, :tour_id
    )
  end

  def load_tour_detail
    @tour_detail = TourDetail.find_by_id params[:id]
    return if @tour_detail
    flash[:danger] = t("controller.flash.load_tour_detail_failed")
    redirect_to root_path
  end
end

app/controllers/tour_details_controller.rb
class TourDetailsController < ApplicationController
  def new
    load_tour_details_data
    @reviews = @tour_detail.tour.reviews.order_by_time_desc.paginate(
      page: params[:page], per_page: Settings.tour_detail_reviews
    )
    @self_review = current_user.reviews.create(tour_id: params[:tour_id])
  end

  private
  def load_tour_details_data
    @tour_detail = TourDetail.find_by_id params[:tour_detail_id]
    @star = @tour_detail.tour.ratings.average(:star).to_i
    @booking_tour = current_user.bookings.create(
      tour_detail_id: params[:tour_detail_id]
    )
    @self_star = current_user.ratings.find_by(tour_id: params[:tour_id])
  end
end

app/views/tour_details/new.html.erb
<div class="container">
  <div class="card">
    <div class="container-fliud">
      <div class="wrapper row">
        <div class="preview col-md-6">
          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1" style="padding-top: 0px;">
              <%= image_tag "#{@tour_detail.tour.image}",  alt: t("views.tag.tour_detail"), class: "group list-group-image", style: "width: 1000px;" %>
            </div>
          </div>
          <ul class="preview-thumbnail nav nav-tabs">
          </ul>
        </div>
        <div class="details col-md-6" style="margin-left: 100px;">
          <h3 class="product-title"> <%= @tour_detail.tour.name %></h3>
          <div class="rating">
            <div class="stars">
              <% if @self_star.nil? %>
                <%= link_to new_rating_path(star: "1", tour_id: @tour_detail.tour.id), remote: true do %>
                  <span class="fa fa-star"></span>
                <% end %>
                <%= link_to new_rating_path(star: "2", tour_id: @tour_detail.tour.id), remote: true do %>
                  <span class="fa fa-star"></span>
                <% end %>
                <%= link_to new_rating_path(star: "3", tour_id: @tour_detail.tour.id), remote: true do %>
                  <span class="fa fa-star"></span>
                <% end %>
                <%= link_to new_rating_path(star: "4", tour_id: @tour_detail.tour.id), remote: true do %>
                  <span class="fa fa-star"></span>
                <% end %>
                <%= link_to new_rating_path(star: "5", tour_id: @tour_detail.tour.id), remote: true do %>
                  <span class="fa fa-star"></span>
                <% end %>
              <% else %>
                <% @self_star.star.times do |star| %>
                  <span class="fa fa-star checked"></span>
                <% end %>
              <% end %>
            </div>
            <span class="review-no"><%= @tour_detail.tour.reviews.all.count %> reviews</span>
          </div>
          <p class="product-description"> <%= @tour_detail.tour.description %></p>
          <h4 class="price"> <%= t("views.tag.current_price") %> <span> <%= @tour_detail.price %> $ </span></h4>
          <p class="vote"> <%= t("views.tag.average") %>
            <% @star.times do |display| %>
              <span class="fa fa-star checked">
              </span>
            <% end %> <%= t("views.tag.of_buyer_enjoyed_this_product")%> <strong>(<%= @tour_detail.tour.ratings.count %> votes)</strong>
          </p>
          <h5 class="sizes"> <%= t("views.tag.time_start") %>
            <span class="size" data-toggle="tooltip" title="small"><%= @tour_detail.time_start %></span>
          </h5>
          <h5 class="sizes"> <%= t("views.tag.time_end") %> :&nbsp;&nbsp;&nbsp;&nbsp;
            <span class="size" data-toggle="tooltip" title="small"><%= @tour_detail.time_end %></span>
          </h5>
          <div class="action" style="display: inline-block">
            <%= form_for(@booking_tour, url: new_booking_path,method: :GET, authenticity_token: true) do |f| %>
              <%= f.text_field(:book_total, class: "add-to-cart", placeholder: "_______", style: "width:70px;") %>
              <%= f.hidden_field :tour_detail_id %>
              <%= button_tag(type: "submit", class: "like btn btn-default", style: "float:left") do %>
                <span class="fa fa-heart"> <%= t("views.tag.booking") %> </span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
<div class="container">
  <h2 class="page-header">Comments</h2>
  <%= form_for(@self_review, url: new_comment_path,method: :GET, authenticity_token: true, remote: true) do |f| %>
    <div class="input-group">
      <%= f.text_field(:content, class: "form-control", placeholder: "Leave a comment ", style: "height: 50px;")%>
      <%= f.hidden_field :tour_id %>
      <span class="input-group-addon">
        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          <i class="fa fa-edit"></i>
        <% end%>
      </span>
    </div>
  <% end%>
  <div class="col-sm-16" id="listcomment">
    <% unless @reviews.nil? %>
      <%= will_paginate @reviews %>
      <% @reviews.each do |review| %>
        <div class="panel panel-white post panel-shadow" id="R<%= review.id%>">
          <div class="post-heading">
            <div class="pull-left image">
              <%= link_to view_other_user_information_path(user_id: review.user.id) do %>
                <%= image_tag "#{review.user.avatar}",  alt: "Tour Image", class: "img-circle avatar" %>
              <% end %>
            </div>
            <% if is_admin? %>
              <%= link_to t("views.tag.delete"),admin_review_path(id: review.id), method: :DELETE, remote: true, class: "btn btn-danger btn-primary icon pull-right",style:"margin-left: 20px;"%>
            <% end %>
            <div class="pull-left meta">
              <div class="title h5">
                <%= link_to view_other_user_information_path(user_id: review.user.id) do %>
                  <b> <%= review.user.name %> </b>
                <% end %>
              </div>
              <h6 class="text-muted time"> <%= review.updated_at %></h6>
            </div>
          </div>
          <div class="post-description">
            <p> <%= review.content%> </p>
            <div class="stats">
              <% if liked? review.id %>
                <%= link_to new_like_path(id: review.id), class: "btn-default stat-item", id: "R#{review.id}L", remote: true do %>
                  <i class="fa fa-thumbs-up icon"></i> <%= review.likes.count%>
                <% end%>
              <% else%>
                <%= link_to like_path(id: review.id), method: "DELETE" , class: "stat-item" ,id: "R#{review.id}L", remote: true do %>
                  <i class="fa fa-thumbs-up icon"></i> <%= review.likes.count%>
                <% end %>
              <%end%>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>