config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

  root "pages#home"
  get "/error", to: "errors#handle404"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/search", to: "pages#search"
  # get "/manage_users", to: "manage_users#new"
  # get "/user_destroy", to: "manage_users#destroy"

  # get "/view_category", to: "manage_categories#index"
  # get "/new_category", to: "manage_categories#new"
  # post "/new_category", to: "manage_categories#create"
  # get "/delete_category", to: "manage_categories#delete"
  
  # get "/new_tour", to: "manage_tours#new"
  # post "/new_tour", to: "manage_tours#create"
  # get "/view_tour", to: "manage_tours#view_all"
  # get "/delete_tour", to: "manage_tours#destroy"

  # get "/new_tour_details", to: "manage_tour_details#new"
  # post "/new_tour_details", to: "manage_tour_details#create"
  # get "/view_tour_details", to: "manage_tour_details#view"
  # get "/delete_tour_details", to: "manage_tour_details#destroy"

  # get "/new_booking_request", to: "booking_request#new"
  # post "/new_booking_request", to: "booking_request#booking"
  # get "/view_booking_request", to: "booking_request#view_all"
  # get "/view_all_booking_request", to: "booking_request#view_all_by_admin"
  # get "/delete_booking_request", to: "booking_request#destroy"

  # get "/review_tour", to: "reviews#new"
  # post "/review_tour", to: "reviews#create"
  # get "/view_all_review", to:"reviews#view_all_reviews"
  # get "/view_tour_review", to: "reviews#view_tour_reviews"
  # get "/edit_my_reviews", to: "reviews#edit"
  # post "/edit_my_reviews", to: "reviews#update"
  # get "/delete_my_reviews", to: "reviews#destroy"
  # post "/like_review", to: "reviews#like"
  # post "/unlike_review", to: "reviews#unlike"

  # post "/pay", to: "payments#pay"

  # get "/revenue", to: "manage_revenue#index"

  get "/view_my_booking", to: "self_management#view_my_booking"
  get "/view_my_review", to: "self_management#view_my_review"
  get "/view_my_information", to: "self_management#view_my_information"
  get "/view_other_user_information", to: "self_management#view_other_user_information"
  resources :self_management, only: [:edit, :update]
  resources :tour_details, only: [:new]
  resources :ratings, only: [:new]
  resources :bookings, only: [:new, :destroy]
  resources :likes, only: [:new, :destroy]
  resources :comments, only: [:new, :destroy]
  resources :users, only: [:new, :edit, :update, :create]
  resources :manage_users, only: [:new, :edit, :update]
  resources :payments, only: [:create]

  namespace :admin do
    resources :users, except: []
    resources :reviews, except: []
    resources :categories, except: []
    resources :tours, except: []
    resources :tour_details, except: []
    resources :bookings, except: []
    resources :payments, only: [:index]
  end
end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tours, dependent: :destroy
  scope :order_by_time_desc, ->{order(created_at: :desc)}
  validates :name, presence: true,
  length: {maximum: Settings.name_maximum_length}
  validates :description, presence: true,
  length: {maximum: Settings.description_maximum_length}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :load_category, only: :destroy

  def index
    @categories = Category.order_by_time_desc.paginate(
      page: params[:page], per_page: Settings.category_per_page
    )
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = t("controller.flash.category_created_successfully")
      redirect_to admin_categories_path
    else
      flash[:danger] = t("controller.flash.category_created_failed")
      render :new
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t("controller.flash.destroy_category_successfully")
    else
      flash[:danger] = t("controller.flash.destroy_category_failed")
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def load_category
    @category = Category.find_by_id params[:id]
    return if @category
    flash[:danger] = t("controller.flash.load_category_failed")
    redirect_to root_path
  end
end

app/views/admin/categories/index.html.erb
<%= will_paginate @categories %>
<div class="container">
  <div class="">
    <table class="table table-striped custab">
      <thead>
        <tr>
          <th> <%= t("views.tag.id") %> </th>
          <th> <%= t("views.tag.category") %> </th>
          <th> <%= t("views.tag.description") %> </th>
          <th class="text-center"> <%= t("views.tag.action") %> </th>
        </tr>
      </thead>
      <% @categories.each do |category| %>
        <tr>
          <td> <%= category.id %> </td>
          <td> <%= category.name %> </td>
          <td> <%= category.description %> </td>
          <td class="text-center">
            <%= link_to new_admin_tour_path(id: category.id), class: "btn btn-info btn-xs" do %>
              <span class="glyphicon glyphicon-edit"> <%= t("views.tag.create_tour") %> </span>
            <% end %>
            <%= link_to admin_category_path(id: category.id), method: :DELETE, class: "btn btn-danger btn-xs" do %>
              <span class="glyphicon glyphicon-remove"> <%= t("views.tag.delete") %> </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<%= link_to t("views.tag.add_new_category"), new_admin_category_path %>

app/views/admin/categories/new.html.erb
<%= form_for(@category, url: admin_categories_path) do |f| %>
  <%= render "shared/form_error_messages", object: @category %>
  <%= f.label t("views.tag.name") %>
  <%= f.text_field :name %>
  <%= f.label t("views.tag.description") %>
  <%= f.text_field :description %>
  <%= f.submit t("views.tag.create"), class: "btn btn-primary" %>
<% end %>