config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

  root "pages#home"
  get "/error", to: "errors#handle404"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/search", to: "pages#search"
  # get "/manage_users", to: "manage_users#new"
  # get "/user_destroy", to: "manage_users#destroy"

  # get "/view_category", to: "manage_categories#index"
  # get "/new_category", to: "manage_categories#new"
  # post "/new_category", to: "manage_categories#create"
  # get "/delete_category", to: "manage_categories#delete"
  
  # get "/new_tour", to: "manage_tours#new"
  # post "/new_tour", to: "manage_tours#create"
  # get "/view_tour", to: "manage_tours#view_all"
  # get "/delete_tour", to: "manage_tours#destroy"

  # get "/new_tour_details", to: "manage_tour_details#new"
  # post "/new_tour_details", to: "manage_tour_details#create"
  # get "/view_tour_details", to: "manage_tour_details#view"
  # get "/delete_tour_details", to: "manage_tour_details#destroy"

  # get "/new_booking_request", to: "booking_request#new"
  # post "/new_booking_request", to: "booking_request#booking"
  # get "/view_booking_request", to: "booking_request#view_all"
  # get "/view_all_booking_request", to: "booking_request#view_all_by_admin"
  # get "/delete_booking_request", to: "booking_request#destroy"

  # get "/review_tour", to: "reviews#new"
  # post "/review_tour", to: "reviews#create"
  # get "/view_all_review", to:"reviews#view_all_reviews"
  # get "/view_tour_review", to: "reviews#view_tour_reviews"
  # get "/edit_my_reviews", to: "reviews#edit"
  # post "/edit_my_reviews", to: "reviews#update"
  # get "/delete_my_reviews", to: "reviews#destroy"
  # post "/like_review", to: "reviews#like"
  # post "/unlike_review", to: "reviews#unlike"

  # post "/pay", to: "payments#pay"

  # get "/revenue", to: "manage_revenue#index"

  get "/view_my_booking", to: "self_management#view_my_booking"
  get "/view_my_review", to: "self_management#view_my_review"
  get "/view_my_information", to: "self_management#view_my_information"
  get "/view_other_user_information", to: "self_management#view_other_user_information"
  resources :self_management, only: [:edit, :update]
  resources :tour_details, only: [:new]
  resources :ratings, only: [:new]
  resources :bookings, only: [:new, :destroy]
  resources :likes, only: [:new, :destroy]
  resources :comments, only: [:new, :destroy]
  resources :users, only: [:new, :edit, :update, :create]
  resources :manage_users, only: [:new, :edit, :update]
  resources :payments, only: [:create]

  namespace :admin do
    resources :users, except: []
    resources :reviews, except: []
    resources :categories, except: []
    resources :tours, except: []
    resources :tour_details, except: []
    resources :bookings, except: []
    resources :payments, only: [:index]
  end
end
end

app/models/tour_detail.rb
class TourDetail < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  has_many :bookings, dependent: :destroy
  scope :order_by_time_desc, ->{order(created_at: :desc)}
  scope :t_id, (lambda do |id|
    where(
      tour_id: id
    )
  end)

  validates :price, numericality:
   {greater_than_or_equal_to: Settings.minimum_price}
  validates :tour_total, numericality:
   {greater_than_or_equal_to: Settings.minimum_tour_total}
  validates :user_id, numericality:
   {greater_than_or_equal_to: Settings.positive}
  validates :tour_id, numericality:
    {
      greater_than_or_equal_to: Settings.positive,
      less_than_or_equal_to: Settings.maximum_tour_total
    }
  validate :validate

  def validate
    if time_start < Time.zone.now
      errors.add(:time_start, I18n.t("validate.validate_time"))
    end
    if time_end <= time_start
      errors.add(:time_end, I18n.t("validate.validate_time_end"))
    end
    true # never return false or the validation fails
  end
end

app/controllers/admin/tour_details_controller.rb
class Admin::TourDetailsController < Admin::BaseController
  before_action :load_tour_detail, only: [:destroy]
  def new
    @tour_details = current_user.tour_details.build(tour_id: params[:id])
  end

  def index
    @tour_details = TourDetail.t_id(params[:id]).order_by_time_desc.paginate(
      page: params[:page], per_page: Settings.tour_detail_per_page
    )
  end

  def create
    @tour_details = current_user.tour_details.create(user_params)
    if @tour_details.save
      flash[:success] = t("controller.flash.tour_detail_created_successfully")
      redirect_to admin_tour_details_path(id: params[:tour_detail][:tour_id])
    else
      flash[:danger] = t("controller.flash.tour_detail_created_failed")
      render :new
    end
  end

  def destroy
    if @tour_detail.destroy
      flash[:success] = t("controller.flash.delete_tour_detail_successfully")
    else
      flash[:danger] = t("controller.flash.delete_tour_detail_failed")
    end
    redirect_to admin_tours_path
  end

  private

  def user_params
    params.require(:tour_detail).permit(
      :price, :tour_total, :time_start, :time_end, :user_id, :tour_id
    )
  end

  def load_tour_detail
    @tour_detail = TourDetail.find_by_id params[:id]
    return if @tour_detail
    flash[:danger] = t("controller.flash.load_tour_detail_failed")
    redirect_to root_path
  end
end

app/controllers/tour_details_controller.rb
class TourDetailsController < ApplicationController
  def new
    load_tour_details_data
    @reviews = @tour_detail.tour.reviews.order_by_time_desc.paginate(
      page: params[:page], per_page: Settings.tour_detail_reviews
    )
    @self_review = current_user.reviews.create(tour_id: params[:tour_id])
  end

  private
  def load_tour_details_data
    @tour_detail = TourDetail.find_by_id params[:tour_detail_id]
    @star = @tour_detail.tour.ratings.average(:star).to_i
    @booking_tour = current_user.bookings.create(
      tour_detail_id: params[:tour_detail_id]
    )
    @self_star = current_user.ratings.find_by(tour_id: params[:tour_id])
  end
end

app/views/admin/tour_details/index.html.erb
<%= will_paginate @tour_details %>
<div class="container">
  <div class="">
    <table class="table table-striped custab">
      <thead>
        <tr>
          <th> <%= t("views.tag.tour_detail_id") %> </th>
          <th> <%= t("views.tag.price") %> </th>
          <th> <%= t("views.tag.tour_total") %> </th>
          <th> <%= t("views.tag.time_start") %> </th>
          <th> <%= t("views.tag.time_end") %> </th>
          <th class="text-center"> <%= t("views.tag.action") %> </th>
        </tr>
      </thead>
      <% @tour_details.each do |tour_detail| %>
        <tr>
          <td>
            <%= link_to new_tour_detail_path(tour_detail_id: tour_detail.id, tour_id: tour_detail.tour.id) do %>
              <%= tour_detail.id %>
            <% end %>
          </td>
          <td> <%= tour_detail.price %> </td>
          <td> <%= tour_detail.tour_total %> </td>
          <td> <%= tour_detail.time_start %> </td>
          <td> <%= tour_detail.time_end %> </td>
          <td class="text-center">
            <%= link_to admin_tour_detail_path(id: tour_detail.id, tour_id: tour_detail.tour_id), method: :DELETE, class: "btn btn-danger btn-xs" do %>
              <span class="glyphicon glyphicon-remove"> <%= t("views.tag.delete") %> </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/tour_details/new.html.erb
<%= form_for(@tour_details, url: admin_tour_details_path) do |f| %>
  <%= render "shared/form_error_messages", object: @tour_details %>
  <%= f.label t("views.tag.price") %>
  <%= f.text_field :price %>
  <%= f.label t("views.tag.tour_total") %>
  <%= f.text_field :tour_total %>
  <br>
  <br>
  <%= f.label t("views.tag.time_start") %>
  <span class="datetime"><%= f.datetime_select :time_start , ampm: true , :class => "form-control"%> <span/>
    <br>
    <%= f.label t("views.tag.time_end") %>
    <span class="datetime"><%= f.datetime_select :time_end , ampm: true , :class => "form-control" %> <span/>
      <br>
      <%= f.hidden_field :tour_id %>
      <%= f.submit t("views.tag.create"), class: "btn btn-primary" %>
    <% end %>